name: plugin_pjmei_components
description: A new Flutter plugin project.
version: 0.0.129
homepage:

environment:
  sdk: '>=3.0.0-218.0.dev <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  pjmei_white_label_dependencies:
    git:
      url: https://bitbucket.org/olawolffdevs/pjmei_white_label_dependencies
      ref: master
      publish_to: none

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  mobx_codegen: ^2.0.1+2
  build_runner: ^2.1.2
  recase: ^4.1.0
  lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/criptografia/